/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.clsAcudiente;
import controlador.clsConexion;
import java.sql.Connection;
/**
 *
 * @author scris
 */
public class frmAcudientes extends javax.swing.JFrame {

    /**
     * Creates new form frmAcudientes
     */
    public frmAcudientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        cerrar();
    }
    //declaracion de atributos
    clsAcudiente objAcu = new clsAcudiente();
    clsConexion objCone = new clsConexion();
    Connection conect = objCone.conectar();
    //metodos 
    //validar
    public void validar() {
        if (txtDocumento.getText().isEmpty()) {
            txtDocumento.grabFocus();
        } else if (txtNombre.getText().isEmpty()) {
            txtNombre.grabFocus();
        } else if (txtApellido.getText().isEmpty()) {
            txtApellido.grabFocus();
        } else if (txtDireccion.getText().isEmpty()) {
            txtDireccion.grabFocus();
        } else if (txtTelefono.getText().isEmpty()) {
            txtTelefono.grabFocus();
        } else if (txtEmail.getText().isEmpty()) {
            txtEmail.grabFocus();
        }     
    }
    //capturarpublic
    public void capturar() {
        objAcu.setDocAcu(txtDocumento.getText());
        objAcu.setNomAcu(txtNombre.getText());
        objAcu.setApeAcu(txtApellido.getText());
        objAcu.setDirAcu(txtDireccion.getText());
        objAcu.setTelAcu(txtTelefono.getText());
        objAcu.setEmaAcu(txtEmail.getText());
    }
    //capturar datos 
    public void capturarDatos() {
        validar();
        capturar();
        objAcu.guardar();
    }
    public void buscarDatos() {
        objAcu.buscarDatos();       
        txtDocumento.setText(objAcu.getDatos()[0]);
        txtNombre.setText(objAcu.getDatos()[1]);
        txtApellido.setText(objAcu.getDatos()[2]);
        txtDireccion.setText(objAcu.getDatos()[3]);
        txtTelefono.setText(objAcu.getDatos()[4]);
        txtEmail.setText(objAcu.getDatos()[5]); 
    }
    //metodo de actualizar
    public void actualizar() {
       validar();
        capturar();
        objAcu.actualizar();
    }
    //cerrar campos
    public void cerrar() {
        txtDocumento.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtEmail.setEnabled(false);
        ButtonGuardar.setEnabled(false);
        ButtonActualizar.setEnabled(false);
    }
    //abrir campos
    public void habilitar() {
        txtDocumento.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtEmail.setEnabled(true);
        ButtonGuardar.setEnabled(true);
    }
        //metodo para limpiar campos 
    public void limpiar() {
        txtDocumento.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");       
    }
    public void verTabla() {
      
      objAcu.verTabla();
      TableEstudiante.setModel(objAcu.getTablaEst());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Documento = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        ButtonNuevo = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEstudiante = new javax.swing.JTable();
        ButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acudiente");

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setForeground(new java.awt.Color(51, 51, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Documento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Documento.setForeground(new java.awt.Color(255, 255, 255));
        Documento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Documento.setText("Documento");
        Background.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 40));

        Nombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        Background.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 30));

        Apellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apellido.setText("Apellido");
        Background.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        Direccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("Direccion");
        Background.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 30));

        Telefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telefono.setText("Telefono");
        Background.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 120, -1));

        Email.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("E-mail");
        Background.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

        txtDocumento.setFont(new java.awt.Font("Segoe Script", 2, 18)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(51, 51, 51));
        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 150, 30));

        txtNombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 30));

        txtApellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        txtDireccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        Background.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, 30));

        txtTelefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 30));

        txtEmail.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, 30));

        ButtonNuevo.setBackground(new java.awt.Color(0, 0, 0));
        ButtonNuevo.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNuevo.setText("Nuevo");
        ButtonNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        ButtonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });
        Background.add(ButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 40));

        ButtonGuardar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonGuardar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonGuardar.setText("Guardar");
        ButtonGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        Background.add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 100, 40));

        ButtonBuscar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBuscar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        Background.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, 40));

        ButtonActualizar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonActualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });
        Background.add(ButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, -1));

        TableEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TableEstudiante.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        TableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableEstudiante);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 200));

        ButtonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonRegresar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegresar.setText("Regresar");
        ButtonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });
        Background.add(ButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        capturarDatos();
        ButtonActualizar.setEnabled(true);
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        actualizar();
        limpiar();
        cerrar();
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        limpiar();
        habilitar();
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        buscarDatos();
        ButtonActualizar.setEnabled(true);
        habilitar();
        verTabla();
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
        frmIndex objInd = new frmIndex();
        objInd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcudientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcudientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcudientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcudientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAcudientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JPanel Background;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTable TableEstudiante;
    private javax.swing.JLabel Telefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
