/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.clsEstudiante;
import controlador.clsConexion;
import java.sql.Connection;


/**
 *
 * @author Christian Henao A.
 */
public class frmEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form frmEstudiantes
     */
    public frmEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
        cerrar();
    }
// Declaracion de variables
    //declaracion variables
    clsEstudiante objEst = new clsEstudiante();
    clsConexion objCone = new clsConexion();
    Connection conect = objCone.conectar();

    //Declaracion de metodos
    //validar
    public void validar() {
        if (txtDocumento.getText().isEmpty()) {
            txtDocumento.grabFocus();
        } else if (txtNombre.getText().isEmpty()) {
            txtNombre.grabFocus();
        } else if (txtApellido.getText().isEmpty()) {
            txtApellido.grabFocus();
        } else if (txtDireccion.getText().isEmpty()) {
            txtDireccion.grabFocus();
        } else if (txtTelefono.getText().isEmpty()) {
            txtTelefono.grabFocus();
        }
    }

    //capturar
    public void capturar() {
        objEst.setDocEst(txtDocumento.getText());
        objEst.setNomEst(txtNombre.getText());
        objEst.setApeEst(txtApellido.getText());
        objEst.setDirEst(txtDireccion.getText());
        objEst.setTelEst(txtTelefono.getText());

    }

    public void capturarDatos() {
        validar();
        capturar();
        objEst.guardar();
    }
//metodo para buscar datos

    public void buscarDatos() {
        objEst.buscarDatos();       
        txtDocumento.setText(objEst.datos[0]);
        txtNombre.setText(objEst.datos[1]);
        txtApellido.setText(objEst.datos[2]);
        txtDireccion.setText(objEst.datos[3]);
        txtTelefono.setText(objEst.datos[4]);
        
    }

    //metodo para limpiar campos 
    public void limpiar() {
        txtDocumento.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
    }

    //cerrar campos
    public void cerrar() {
        txtDocumento.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        ButtonGuardar.setEnabled(false);
        ButtonActualizar.setEnabled(false);
        ButtonImprimir.setEnabled(false);
    }

    //abrir campos
    public void habilitar() {
        txtDocumento.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        ButtonGuardar.setEnabled(true);
    }

    //metodo de actualizar
    public void actualizar() {
       validar();
        capturar();
        objEst.actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        ButtonNuevo = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonImprimir = new javax.swing.JButton();
        ButtonRegresar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiante");
        setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDocumento.setBackground(new java.awt.Color(51, 51, 51));
        txtDocumento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(51, 204, 255), null, null));
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDocumento.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, 30));

        Documento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Documento.setForeground(new java.awt.Color(0, 0, 0));
        Documento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Documento.setText("Documento"); // NOI18N
        Documento.setToolTipText("");
        jPanel1.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 40));

        Nombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 40));

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 30));

        Apellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apellido.setText("Apellido");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, 30));

        txtApellido.setBackground(new java.awt.Color(51, 51, 51));
        txtApellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 30));

        Direccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(0, 0, 0));
        Direccion.setText("Dirección");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        txtDireccion.setBackground(new java.awt.Color(51, 51, 51));
        txtDireccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, 30));

        Telefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setText("Teléfono");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 90, -1));

        txtTelefono.setBackground(new java.awt.Color(51, 51, 51));
        txtTelefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 170, 30));

        ButtonNuevo.setBackground(new java.awt.Color(0, 102, 204));
        ButtonNuevo.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNuevo.setText("Nuevo");
        ButtonNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, -1));

        ButtonGuardar.setBackground(new java.awt.Color(0, 102, 204));
        ButtonGuardar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonGuardar.setText("Guardar");
        ButtonGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 100, -1));

        ButtonBuscar.setBackground(new java.awt.Color(0, 102, 204));
        ButtonBuscar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, 40));

        ButtonActualizar.setBackground(new java.awt.Color(0, 102, 204));
        ButtonActualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 110, 40));

        ButtonImprimir.setBackground(new java.awt.Color(0, 102, 204));
        ButtonImprimir.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonImprimir.setText("Imprimir");
        ButtonImprimir.setActionCommand("Imprimir");
        ButtonImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 270, 40));

        ButtonRegresar.setBackground(new java.awt.Color(0, 102, 204));
        ButtonRegresar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonRegresar.setText("Regresar");
        ButtonRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 0, 120, 40));

        background.setBackground(new java.awt.Color(0, 255, 255));
        background.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        background.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        limpiar();
        habilitar();
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        capturarDatos();
        ButtonActualizar.setEnabled(true);

    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        buscarDatos();
        ButtonActualizar.setEnabled(true);
        habilitar();
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        actualizar();
        limpiar();
        cerrar();
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
        frmIndex objInd = new frmIndex();
        objInd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
