/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author scris
 */
public class frmIndex extends javax.swing.JFrame {

    /**
     * Creates new form frmIndex
     */
    public frmIndex() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        ButtonEstudiante = new javax.swing.JButton();
        ButtonAcudiente = new javax.swing.JButton();
        ButtonProfesor = new javax.swing.JButton();
        ButtonMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indice");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        setResizable(false);

        background.setBackground(new java.awt.Color(153, 204, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonEstudiante.setBackground(new java.awt.Color(0, 255, 255));
        ButtonEstudiante.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        ButtonEstudiante.setText("Estudiante");
        ButtonEstudiante.setBorder(null);
        ButtonEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEstudianteActionPerformed(evt);
            }
        });
        background.add(ButtonEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 130));

        ButtonAcudiente.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonAcudiente.setText("Acudiente");
        ButtonAcudiente.setBorder(null);
        ButtonAcudiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAcudienteActionPerformed(evt);
            }
        });
        background.add(ButtonAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 270, 130));

        ButtonProfesor.setBackground(new java.awt.Color(0, 0, 0));
        ButtonProfesor.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonProfesor.setForeground(new java.awt.Color(255, 255, 255));
        ButtonProfesor.setText("Profesor");
        ButtonProfesor.setBorder(null);
        ButtonProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProfesorActionPerformed(evt);
            }
        });
        background.add(ButtonProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 130));

        ButtonMateria.setBackground(new java.awt.Color(0, 255, 255));
        ButtonMateria.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonMateria.setForeground(new java.awt.Color(0, 0, 0));
        ButtonMateria.setText("Materia");
        ButtonMateria.setBorder(null);
        ButtonMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMateriaActionPerformed(evt);
            }
        });
        background.add(ButtonMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 270, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEstudianteActionPerformed
        // TODO add your handling code here:
        frmEstudiantes objEst = new frmEstudiantes();
        objEst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonEstudianteActionPerformed

    private void ButtonAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAcudienteActionPerformed
        // TODO add your handling code here
        frmAcudientes objAcu = new frmAcudientes();
        objAcu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonAcudienteActionPerformed

    private void ButtonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProfesorActionPerformed
        // TODO add your handling code here
        frmProfesores objPro = new frmProfesores();
        objPro.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ButtonProfesorActionPerformed

    private void ButtonMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMateriaActionPerformed
        // TODO add your handling code here:
        frmMateria objMat = new frmMateria();
        objMat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAcudiente;
    private javax.swing.JButton ButtonEstudiante;
    private javax.swing.JButton ButtonMateria;
    private javax.swing.JButton ButtonProfesor;
    private javax.swing.JPanel background;
    // End of variables declaration//GEN-END:variables
}
