/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.clsMateria;
import controlador.clsConexion;
import java.sql.Connection;


/**
 *
 * @author scris
 */
public class frmMateria extends javax.swing.JFrame {

    /**
     * Creates new form frmMateria
     */
    public frmMateria() {
        initComponents();
          this.setLocationRelativeTo(null);
        cerrar();
    }
//atributos 
    clsMateria objMat = new clsMateria();
    clsConexion objCone = new clsConexion();
    Connection conect = objCone.conectar();
    //metodos
    public void validar() {
        if (txtNombre.getText().isEmpty()) {
            txtNombre.grabFocus();
        } else if (ComboGrado.getSelectedIndex() == 0) {
            ComboGrado.grabFocus();
        }
    }
    public void capturar() {
        objMat.setCodMat(Byte.parseByte(txtDocumento.getText()));
        objMat.setNomMat(txtNombre.getText());
        objMat.setGraMat(ComboGrado.getSelectedItem().toString());
    }
     public void capturar2() {
        
        objMat.setNomMat(txtNombre.getText());
        objMat.setGraMat(ComboGrado.getSelectedItem().toString());
    }
     

    public void capturarDatos() {
        validar();
        capturar2();
        objMat.guardar();
      
    }
//metodo de busqueda
    public void buscarDatos() {
     objMat.buscarDatos();
     txtDocumento.setText(objMat.datos[0]);
     txtNombre.setText(objMat.datos[1]);
    }
//metodo de actualizar
    public void actualizar() {
        validar();
        capturar();
        objMat.actualizar();
        
        /*try {

            objCone.Sql = objCone.con.prepareStatement("UPDATE materia  SET nomMat='" + txtNombre.getText() + "', graMat='" + ComboGrado.getSelectedItem().toString() + "' WHERE codMat='" + Byte.parseByte(txtDocumento.getText()) + "'");

            objCone.Sql.executeUpdate();
            objCone.cerrar();
            JOptionPane.showMessageDialog(null, "Registro actualizado con éxito");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar:");
        }*/
    }
    //limpiar campos
    public void limpiar() {
        txtDocumento.setText("");
        txtNombre.setText("");
    }

    //abrir campos
    public void habilitar() {
        txtDocumento.setEnabled(true);
        txtNombre.setEnabled(true);
        ComboGrado.setEnabled(true);
        ButtonGuardar.setEnabled(true);
    }

    //cerrar campos
    public void cerrar() {
        txtDocumento.setEnabled(false);
        txtNombre.setEnabled(false);
        ComboGrado.setEnabled(false);
        ButtonGuardar.setEnabled(false);
        ButtonActualizar.setEnabled(false);
        ButtonImprimir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoMateria = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Grado = new javax.swing.JLabel();
        ComboGrado = new javax.swing.JComboBox<>();
        ButtonNuevo = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonImprimir = new javax.swing.JButton();
        ButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Materia");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoMateria.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        codigoMateria.setForeground(new java.awt.Color(0, 0, 0));
        codigoMateria.setText("Codigo Materia");
        jPanel1.add(codigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 30));

        txtDocumento.setBackground(new java.awt.Color(51, 51, 51));
        txtDocumento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, 30));

        nombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setText(" Nombre Materia");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 30));

        Grado.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Grado.setForeground(new java.awt.Color(0, 0, 0));
        Grado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Grado.setText("Grado");
        jPanel1.add(Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, -1));

        ComboGrado.setBackground(new java.awt.Color(51, 51, 51));
        ComboGrado.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ComboGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Grado 1", "Grado 2", "Grado 3", "Grado 4", "Grado 5" }));
        ComboGrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ComboGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ComboGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, 30));

        ButtonNuevo.setBackground(new java.awt.Color(0, 204, 204));
        ButtonNuevo.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNuevo.setText("Nuevo");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 40));

        ButtonGuardar.setBackground(new java.awt.Color(0, 204, 204));
        ButtonGuardar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 40));

        ButtonBuscar.setBackground(new java.awt.Color(0, 204, 204));
        ButtonBuscar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 40));

        ButtonActualizar.setBackground(new java.awt.Color(0, 204, 204));
        ButtonActualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        ButtonImprimir.setBackground(new java.awt.Color(0, 204, 204));
        ButtonImprimir.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonImprimir.setForeground(new java.awt.Color(51, 51, 51));
        ButtonImprimir.setText("Imprimir");
        ButtonImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 330, 30));

        ButtonRegresar.setBackground(new java.awt.Color(0, 204, 204));
        ButtonRegresar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonRegresar.setForeground(new java.awt.Color(51, 51, 51));
        ButtonRegresar.setText("Regresar");
        ButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 0, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
       limpiar();
        habilitar();
        txtDocumento.setEnabled(false);
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
       
        capturarDatos();
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        buscarDatos();
        ButtonActualizar.setEnabled(true);
        habilitar();
        txtDocumento.setEnabled(false);
        
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
          actualizar();
        limpiar();
        cerrar();
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
         frmIndex objInd = new frmIndex();
        objInd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JComboBox<String> ComboGrado;
    private javax.swing.JLabel Grado;
    private javax.swing.JLabel codigoMateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
