/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.clsProfesor;
import controlador.clsConexion;
import java.sql.Connection;


/**
 *
 * @author Christian Henao 
 */
public class frmProfesores extends javax.swing.JFrame {

    /**
     * Creates new form frmProfesores
     */
    public frmProfesores() {
        initComponents();
        this.setLocationRelativeTo(null);
        cerrar();
    }
    //declaracion de atributos
    clsProfesor objPro = new clsProfesor();
    clsConexion objCone = new clsConexion();
    Connection conect = objCone.conectar();
   
    //metodos 
    //validar
    public void validar() {
        if (txtDocumento.getText().isEmpty()) {
            txtDocumento.grabFocus();
        } else if (txtNombre.getText().isEmpty()) {
            txtNombre.grabFocus();
        } else if (txtApellido.getText().isEmpty()) {
            txtApellido.grabFocus();
        } else if (txtDireccion.getText().isEmpty()) {
            txtDireccion.grabFocus();
        } else if (txtTelefono.getText().isEmpty()) {
            txtTelefono.grabFocus();
        } else if (txtEmail.getText().isEmpty()) {
            txtEmail.grabFocus();
        } else if (ComboTitulo.getSelectedIndex() == 0) {
            ComboTitulo.grabFocus();    
    }}
    //capturar
    public void capturar() {
        objPro.setDocPro(txtDocumento.getText());
        objPro.setNomPro(txtNombre.getText());
        objPro.setApePro(txtApellido.getText());
        objPro.setDirPro(txtDireccion.getText());
        objPro.setTelPro(txtTelefono.getText());
        objPro.setEmaPro(txtEmail.getText());
        objPro.setTitPro(ComboTitulo.getSelectedItem().toString());

    }
    public void capturarDatos() {
        validar();
        capturar();
        objPro.guardar();
    
    }
    public void buscarDatos() {
        objPro.buscarDatos();       
        txtDocumento.setText(objPro.getDatos()[0]);
        txtNombre.setText(objPro.getDatos()[1]);
        txtApellido.setText(objPro.getDatos()[2]);
        txtDireccion.setText(objPro.getDatos()[3]);
        txtTelefono.setText(objPro.getDatos()[4]);
        txtEmail.setText(objPro.getDatos()[5]);
        //ComboTitulo.setEditable(true).setText(objPro.datos[6]);
        
    }
    //metodo de actualizar
    public void actualizar() {
       validar();
        capturar();
        objPro.actualizar();
    }
    //cerrar campos
    public void cerrar() {
        txtDocumento.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtEmail.setEnabled(false);
        ComboTitulo.setEnabled(false);
        ButtonGuardar.setEnabled(false);
        ButtonActualizar.setEnabled(false);
        ButtonImprimir.setEnabled(false);
    }
    //abrir campos
    public void habilitar() {
        txtDocumento.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtEmail.setEnabled(true);
        ComboTitulo.setEnabled(true);
        ButtonGuardar.setEnabled(true);
    }
        //metodo para limpiar campos 
    public void limpiar() {
        txtDocumento.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        
    }
    public void verTabla() {
      
      objPro.verTabla();
      TableMateria.setModel(objPro.getTablaMat());
      
    }

    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Documento = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        ButtonNueva = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonImprimir = new javax.swing.JButton();
        ComboTitulo = new javax.swing.JComboBox<>();
        ToggleRegresar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMateria = new javax.swing.JTable();
        ButtonIr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profesor");
        setBackground(new java.awt.Color(50, 33, 35));

        background.setBackground(new java.awt.Color(51, 51, 51));
        background.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDocumento.setBackground(new java.awt.Color(102, 102, 102));
        txtDocumento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, 30));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, -1));

        Documento.setBackground(new java.awt.Color(255, 255, 255));
        Documento.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Documento.setForeground(new java.awt.Color(255, 255, 255));
        Documento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Documento.setText("Documento");
        jPanel1.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 105, 45));

        Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Direccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("Dirección");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        Apellido.setBackground(new java.awt.Color(255, 255, 255));
        Apellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apellido.setText("Apellido");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 20));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("E-mail");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 80, -1));

        Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Telefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setText("teléfono");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, -1));

        txtApellido.setBackground(new java.awt.Color(102, 102, 102));
        txtApellido.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 180, 30));

        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, 30));

        txtTelefono.setBackground(new java.awt.Color(102, 102, 102));
        txtTelefono.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 30));

        txtDireccion.setBackground(new java.awt.Color(102, 102, 102));
        txtDireccion.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 180, 30));

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 180, 30));

        ButtonNueva.setBackground(new java.awt.Color(255, 255, 255));
        ButtonNueva.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonNueva.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNueva.setText("Nuevo");
        ButtonNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 100, 40));

        ButtonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonGuardar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonGuardar.setText("Guardar");
        ButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 120, 40));

        ButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBuscar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 110, 40));

        ButtonActualizar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonActualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 130, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 100, 40));

        ButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        ButtonImprimir.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonImprimir.setForeground(new java.awt.Color(0, 0, 0));
        ButtonImprimir.setText("Imprimir");
        ButtonImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 270, 40));

        ComboTitulo.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ComboTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ComboTitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Tecnico", "Tecnologo", "Profesional", "Especialista", "Magister", "Doctor" }));
        ComboTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTituloActionPerformed(evt);
            }
        });
        jPanel1.add(ComboTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 40));

        ToggleRegresar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ToggleRegresar.setForeground(new java.awt.Color(0, 0, 0));
        ToggleRegresar.setText("Regresar");
        ToggleRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ToggleRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(ToggleRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jTabbedPane1.addTab("Profesor", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonVer.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonVer.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVer.setText("Ver");
        ButtonVer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, 40));

        TableMateria.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        TableMateria.setForeground(new java.awt.Color(0, 0, 0));
        TableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableMateria);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 140, 570, 300));

        ButtonIr.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ButtonIr.setForeground(new java.awt.Color(0, 0, 0));
        ButtonIr.setText("Ir Materias");
        ButtonIr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonIr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIrActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonIr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 140, 40));

        jTabbedPane1.addTab("Materias Profesor", jPanel2);

        background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void ComboTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTituloActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        capturarDatos();
        ButtonActualizar.setEnabled(true);
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        buscarDatos();
        ButtonActualizar.setEnabled(true);
        habilitar();
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        actualizar();
        limpiar();
        cerrar();
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevaActionPerformed
        limpiar();
        habilitar();
    }//GEN-LAST:event_ButtonNuevaActionPerformed

    private void ToggleRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleRegresarActionPerformed
        frmIndex objInd = new frmIndex();
        objInd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ToggleRegresarActionPerformed

    private void ButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerActionPerformed
     verTabla();
    }//GEN-LAST:event_ButtonVerActionPerformed

    private void ButtonIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIrActionPerformed
        frmMateria objMat = new frmMateria();
        objMat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonIrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonIr;
    private javax.swing.JButton ButtonNueva;
    private javax.swing.JButton ButtonVer;
    private javax.swing.JComboBox<String> ComboTitulo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTable TableMateria;
    private javax.swing.JLabel Telefono;
    private javax.swing.JToggleButton ToggleRegresar;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
